import { WebRequest } from "webextension-polyfill-ts";
import { bytesToBase64 } from "byte-base64";
import { RawCertificate } from "../../../shared/types/certificate/RawCertificate";

/**
 * Class which provides functionality regarding the creation of certificates.
 */
export abstract class CertificateFactory {
  /**
   * Takes the security info generated by Firefox and converts it into a
   * {@link RawCertificate}.
   *
   * @param securityInfo The browser security info to be converted.
   */
  public static fromSecurityInfo(
    securityInfo: WebRequest.SecurityInfo
  ): RawCertificate {
    const certificateInfo = securityInfo.certificates[0];
    const prefix = "-----BEGIN CERTIFICATE-----";
    const postfix = "-----END CERTIFICATE-----";
    let pemCertificate = "";
    if (certificateInfo.rawDER !== undefined) {
      pemCertificate = prefix + bytesToBase64(certificateInfo.rawDER) + postfix;
    }
    return new RawCertificate(pemCertificate);
  }
}
